INSERT INTO tree (scientific_name, common_name) VALUES
                                                    ('Alberta magna', 'Natal Flame Bush'),
                                                    ('Albizia adianthifolia', 'Flat-crown'),
                                                    ('Allophylus natalensis', 'Dune Allophylus'),
                                                    ('Anthocleista grandiflora', 'Forest Fever Tree'),
                                                    ('Apodytes dimidiata', 'White Pear'),
                                                    ('Brachylaena discolor', 'Coast Silver Oak'),
                                                    ('Calodendrum capense', 'Cape Chestnut'),
                                                    ('Canthium mundianum', 'Rock Alder'),
                                                    ('Cassine peragua', 'Cape Saffron'),
                                                    ('Combretum kraussii', 'Forest Bushwillow'),
                                                    ('Cryptocarya woodii', 'Cape Laurel'),
                                                    ('Cunonia capensis', 'Red Alder'),
                                                    ('Curtisia dentata', 'Assegai'),
                                                    ('Ekebergia capensis', 'Cape Ash'),
                                                    ('Erythrina caffra', 'Coastal Coral Tree'),
                                                    ('Ficus bizanae', 'Pondo Fig'),
                                                    ('Ficus craterostoma', 'Forest Fig'),
                                                    ('Ficus natalensis', 'Natal Fig'),
                                                    ('Ficus sur', 'Broom Cluster Fig'),
                                                    ('Ficus trichopoda', 'Swamp Fig'),
                                                    ('Harpephyllum caffrum', 'Wild Plum'),
                                                    ('Ilex mitis', 'African Holly'),
                                                    ('Maytenus acuminata', 'Silky Bark'),
                                                    ('Millettia grandis', 'Umzimbeet'),
                                                    ('Millettia sutherlandii', 'Giant Umzimbeet'),
                                                    ('Mimusops caffra', 'Coast Red Milkwood'),
                                                    ('Mimusops obovata', 'Red Milkwood'),
                                                    ('Nuxia floribunda', 'Forest Nuxia'),
                                                    ('Podocarpus falcatus', 'Outeniqua Yellowwood'),
                                                    ('Podocarpus henkelii', 'Natal Yellowwood'),
                                                    ('Podocarpus latifolius', 'Yellowwood'),
                                                    ('Prunus africana', 'Red Stinkwood'),
                                                    ('Rapanea melanophloeos', 'Cape Beech'),
                                                    ('Rothmannia capensis', 'Cape Gardenia'),
                                                    ('Schefflera umbellifera', 'Forest Cabbage Tree'),
                                                    ('Syzygium gerrardii', 'Forest Waterberry'),
                                                    ('Trema orientalis', 'Pigeon Wood'),
                                                    ('Trichilia dregeana', 'Forest Mahogany'),
                                                    ('Vepris lanceolata', 'White Ironwood'),
                                                    ('Virgilia divaricata', 'Keurboom'),
                                                    ('Warburgia salutaris', 'Pepperbark Tree');
